--!csp build system based on xmake
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- You may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Copyright (C) 2022-2023 xqyjlj<xqyjlj@126.com>
--
-- @author      xqyjlj
-- @file        logo.lua
--
-- Change Logs:
-- Date           Author       Notes
-- ------------   ----------   -----------------------------------------------
-- 2023-01-02     xqyjlj       initial version
--

import("csp.devel.git")

local logo =
    [[
      ______________ 
     / ___/ ___/ __ \
    / /__/__  / /_/ /
    \___/____/ .___/ 
            /_/      
                by xqyjlj<xqyjlj@126.com>
]]

local manual = "https://csplink.top/#/getting_started"
local donate = "https://csplink.top/#/sponsor"
local copyright = "Copyright (C) 2022-2023 xqyjlj<xqyjlj@126.com>"

function show()
    local repo_builtinvars = git.get_builtinvars(os.scriptdir())
    cprint(
        "${bright}csp build system %s+%s.%s, A cross-platform build system based on xmake",
        repo_builtinvars["git_tag"],
        repo_builtinvars["git_branch"],
        repo_builtinvars["git_commit"]
    )
    cprint(copyright)
    cprint("${bright green}" .. logo)
    cprint("    ${point_right}  ${bright}Manual${clear}: ${underline}%s${clear}", manual)
    cprint("    ${pray}  ${bright}Donate${clear}: ${underline}%s${clear}", donate)
end

function get_logo()
    return logo
end

function get_header()
    local header = {}
    local repo_builtinvars = git.get_builtinvars(os.scriptdir())
    local sdk_builtinvars = git.get_builtinvars(os.projectdir())
    local title =
        string.format(
        "csp build system %s+%s.%s, A cross-platform build system based on xmake",
        repo_builtinvars["git_tag"],
        repo_builtinvars["git_branch"],
        repo_builtinvars["git_commit"]
    )
    table.insert(header, "This file is automatically generated by the csp build system! Do not change!")
    table.insert(header, " ")
    table.insert(header, title)
    table.insert(header, copyright)
    for _, line in ipairs(logo:split("\n")) do
        table.insert(header, line)
    end

    -- sdk urls
    table.insert(header, " ")
    table.insert(header, "manual: " .. manual)
    table.insert(header, "donate: " .. donate)

    -- repos vars
    table.insert(header, " ")
    table.insert(header, "repos vars: ")
    for _, k in pairs(table.orderkeys(repo_builtinvars)) do
        table.insert(header, "    " .. k .. ": " .. repo_builtinvars[k])
    end

    -- sdk vars
    table.insert(header, " ")
    table.insert(header, "sdk vars: ")
    for _, k in pairs(table.orderkeys(sdk_builtinvars)) do
        table.insert(header, "    " .. k .. ": " .. sdk_builtinvars[k])
    end
    return table.concat(header, "\n")
end
