--!csp build system based on xmake
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- You may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Copyright (C) 2022-2023 xqyjlj<xqyjlj@126.com>
--
-- @author      xqyjlj
-- @file        config_on_config.lua
--
-- Change Logs:
-- Date           Author       Notes
-- ------------   ----------   -----------------------------------------------
-- 2023-01-02     xqyjlj       initial version
--

import("core.base.option")
import("core.project.config")
import("core.project.project")
import("lib.detect.find_tool")

local logo =
    [[

          ______________ 
         / ___/ ___/ __ \
        / /__/__  / /_/ /
        \___/____/ .___/ 
                /_/      
                        by xqyjlj<xqyjlj@126.com>
]]

local manual = "https://csplink.top/#/getting_started"
local donate = "https://csplink.top/#/sponsor"
local title = ""
local copyright = "Copyright (C) 2022-present xqyjlj<xqyjlj@126.com>"
local footer =
    [[
    ${point_right}  ${bright}Manual${clear}: ${underline}${{manual}}${clear}
    ${pray}  ${bright}Donate${clear}: ${underline}${{donate}}${clear}
]]

local repo_builtinvars = {}
local sdk_builtinvars = {}

function pairs_by_keys(t)
    local a = {}
    for n in pairs(t) do
        a[#a + 1] = n -- create temporary tables
    end
    table.sort(a)
    local i = 0
    return function()
        i = i + 1
        return a[i], t[a[i]]
    end
end

-- export
function save()
    local configs = {}
    for optname, opt in pairs_by_keys(project.options()) do
        if opt:info().showmenu then
            configs[optname] = opt:value()
        end
    end
    return io.save("csp.conf", configs, {orderkeys = true})
end

function get_git_builtinvars()
    local builtinvars = {}
    local cmds = {
        git_tag = "git describe --tags",
        git_tag_long = "git describe --tags --long",
        git_branch = "git rev-parse --abbrev-ref HEAD",
        git_commit = "git rev-parse --short HEAD",
        git_commit_long = "git rev-parse HEAD",
        git_commit_date = "git log -1 --date=format:%Y%m%d%H%M%S --format=%ad"
    }
    local git = find_tool("git")
    if git then
        for name, argv in pairs(cmds) do
            local result
            result =
                try {
                function()
                    return os.iorun(argv)
                end
            }
            if not result then
                result = "none"
            end
            builtinvars[name] = result:trim()
        end
    else
        builtinvars[name] = "not find git, please install git and add it to PATH."
    end
    return builtinvars
end

function generate_header()
    local header = {}
    for optname, opt in pairs_by_keys(project.options()) do
        if opt:info().showmenu then
            local info = {}
            local key = "/"

            -- init info object
            info.name = optname
            info.description = opt:info().description
            -- convert boolean to 1 and 0
            if opt:value() == true then
                info.value = 1
            elseif opt:value() == false then
                info.value = 0
            else
                info.value = opt:value()
            end

            if opt:info().category then
                key = opt:info().category
            else
                key = "/" -- if not use set_category, then use default "/"
            end

            if not header[key] then
                header[key] = {} -- create new info table
            end

            header[key][info.name] = info
        end
    end
    return header
end

function get_repo_builtinvars()
    os.cd(os.scriptdir())
    local builtinvars = get_git_builtinvars()
    os.cd(os.projectdir())
    return builtinvars
end

function get_sdk_builtinvars()
    local builtinvars = get_git_builtinvars()
    return builtinvars
end

function generate_file(header)
    local t = {}
    table.insert(t, "/** ")
    table.insert(t, " * This file is automatically generated by the csp build system! Do not change!")
    table.insert(t, " *")
    table.insert(t, " * " .. title)
    table.insert(t, " * " .. copyright)
    for _, line in ipairs(logo:split("\n")) do
        table.insert(t, " * " .. line)
    end

    -- sdk urls
    table.insert(t, " *")
    table.insert(t, " * manual: " .. manual)
    table.insert(t, " * donate: " .. donate)

    -- repos vars
    table.insert(t, " *")
    table.insert(t, " * repos vars: ")
    for k, v in pairs_by_keys(repo_builtinvars) do
        table.insert(t, " *    " .. k .. ": " .. v)
    end

    -- sdk vars
    table.insert(t, " *")
    table.insert(t, " * sdk vars: ")
    for k, v in pairs_by_keys(sdk_builtinvars) do
        table.insert(t, " *    " .. k .. ": " .. v)
    end
    table.insert(t, " */") -- end

    -- macro
    table.insert(t, "#ifndef __CSP_CONFIG_H__")
    table.insert(t, "#define __CSP_CONFIG_H__")
    table.insert(t, "")
    for k, v in pairs_by_keys(sdk_builtinvars) do
        table.insert(t, "#define CSP_" .. k:upper() .. ' "' .. v .. '"')
    end

    for mk, mv in pairs_by_keys(header) do
        table.insert(t, "\n/* " .. mk .. " */")
        for k, v in pairs_by_keys(mv) do
            local description = ""
            local value = ""
            if v.description then
                description = " /* " .. v.description .. " */" -- add description
            end
            if type(v.value) == "string" then
                value = '"' .. v.value .. '"' -- string should be wrapped with ""
            else
                value = v.value
            end
            table.insert(t, "#define " .. k .. " " .. value .. description)
        end
    end
    table.insert(t, "\n#endif")
    return table.concat(t, "\n") .. "\n"
end

function show_logo()
    cprint("${bright green}" .. logo)
    footer = footer:gsub("${{manual}}", manual)
    footer = footer:gsub("${{donate}}", donate)
    cprint(footer)
end

function main(target)
    if not option.get("menu") then
        return
    end

    repo_builtinvars = get_repo_builtinvars()
    sdk_builtinvars = get_sdk_builtinvars()
    title =
        string.format(
        "csp build system %s+%s.%s, A cross-platform build system based on xmake",
        repo_builtinvars["git_tag"],
        repo_builtinvars["git_branch"],
        repo_builtinvars["git_commit"]
    )

    cprint("${bright}" .. title)
    cprint("${bright}" .. copyright)
    show_logo()
    cprint("${bright green}config complete!")

    save() -- export config to ${projectdir}/csp.conf
    local data = generate_file(generate_header())
    io.writefile("$(buildir)/csp_conf.h", data)
end
